<a href="https://colab.research.google.com/github/Huyen-005/THDeepLearning/blob/Tuan1/Tuan1_Numpy_Pandas_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
#tạo array 1 chiều
#cách 1
#tạo list
my_list = [1 , 9 , 15, 39]
print('Python list :', my_list)
#chuyển list -->Numpy
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)
#cách 2
a = np.array([1, 9, 15, 39])
print(a)
print(a.shape)
print(a.dtype)
# 3.2 Array 2 chiều
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nArray 2 chiều:\n", b)

# 3.3 Array 3 chiều
c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
print("\nArray 3 chiều:\n", c)

# 3.4 Array toàn 0 và 1
zeros = np.zeros((2,3))
ones = np.ones((2,3))
print("\nMa trận 0:\n", zeros)
print("Ma trận 1:\n", ones)

# 3.5 Reshape & Flatten
a2 = np.array([1,2,3,4,5,6])
reshape = a2.reshape((2,3))
print("\nReshape:\n", reshape)

flatten = reshape.flatten()
print("Flatten:", flatten)

# 3.6 hstack & vstack
x = np.array([1,2,3])
y = np.array([4,5,6])
print("\nhstack:", np.hstack((x,y)))
print("vstack:\n", np.vstack((x,y)))

# 3.7 Random
rand_int = np.random.randint(1, 10, size=(2,3))
rand_float = np.random.rand(2,3)
rand_norm = np.random.normal(loc=0, scale=1, size=5)
choice = np.random.choice([10,20,30,40])

print("\nRandom int:\n", rand_int)
print("Random float:\n", rand_float)
print("Random normal:", rand_norm)
print("Random choice:", choice)

# 3.8 Thay đổi giá trị
a3 = np.array([1,2,3])
a3[0] = 100
print("\nSau khi thay đổi:", a3)

# 3.9 arange & linspace
print("\narange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))

# 3.10 Index & Slice
a4 = np.array([[1,2,3],
               [4,5,6]])
print("\na[0,1]:", a4[0,1])
print("Cột 1:", a4[:,1])
print("Dòng 1:", a4[1,:])

Python list : [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]
(4,)
int64

Array 2 chiều:
 [[1 2 3]
 [4 5 6]]

Array 3 chiều:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Ma trận 0:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ma trận 1:
 [[1. 1. 1.]
 [1. 1. 1.]]

Reshape:
 [[1 2 3]
 [4 5 6]]
Flatten: [1 2 3 4 5 6]

hstack: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]

Random int:
 [[1 2 4]
 [8 4 9]]
Random float:
 [[0.95937955 0.89238425 0.34602958]
 [0.69448251 0.05158722 0.18198398]]
Random normal: [ 0.07666841  0.48692362 -1.06232092 -0.38726299 -0.1793047 ]
Random choice: 20

Sau khi thay đổi: [100   2   3]

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]

a[0,1]: 2
Cột 1: [2 5]
Dòng 1: [4 5 6]


In [8]:
import pandas as pd
import numpy as np

print("Pandas từ series từ list")

# Series từ list
a = pd.Series([1., 2., 3.])
print(a)
print("First value:", a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print("First value:", b['a'])

# Series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

print("\n2. NUMPY <-> PANDAS")
# Numpy -> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print("DataFrame:\n", df_h)
# Pandas -> Numpy
numpy_h = np.array(df_h)
print("Numpy array:\n", numpy_h)

print("\n 3. DATAFRAME")

# DataFrame có tên cột
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

# Tạo DataFrame 20x4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

print("\n 4. SLICE DATAFRAME ")
#chọn 1 cột
print("Cột so1:\n", df['so1'])
#chọ nhìu dòng
print("Chọn nhiều dòng :\n", df[0:3])
#chọn nhiều cột
print("Chọn nhiều cột :\n",df[['so1','so3']])
#Chọn nhiều dòng , nhiều cột
print("Chọn nhiều dòng , nhiều cột \n",df.iloc[:3 , :2])
#xóa cột
df = df.drop(columns=['so1','so4'])
print(df)
print("Lọc > 0:\n", df[df > 0])

print("\n 5. NỐI DATAFRAME")
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])
df_concat = pd.concat([df1, df2])
print("Concate DataFrame:\n", df_concat)

print("\n 6. XỬ LÝ DATA ")
# Xóa trùng
print("Drop duplicates:\n", df_concat.drop_duplicates('Name'))
# Sắp xếp
print("Sort theo Age:\n", df_concat.sort_values('Age'))
# Đổi tên cột
df_rename = df_concat.rename(columns={
    'Name': 'Surname',
    'Age': 'Age_pupil'
})
print("Rename:\n", df_rename)

print("\n===== 7. CSV =====")
# Lưu CSV
df_concat.to_csv("data.csv", index=False)
# Đọc CSV
df_csv = pd.read_csv("data.csv")
print(df_csv)

print("\n===== 8. GROUPBY =====")
data = {
    "Species": ["Cat", "Dog", "Cat", "Dog"],
    "Weight": [4, 10, 5, 12]
}
df_group = pd.DataFrame(data)
# GroupBy object
group = df_group.groupby("Species")
print("Mean theo Species:\n", group.mean(numeric_only=True))
print("Max theo Species:\n", group.max(numeric_only=True))
print("Count theo Species:\n", group.count())

print("\n===== HOÀN THÀNH =====")

Pandas từ series từ list
0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64

2. NUMPY <-> PANDAS
DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]

 3. DATAFRAME
    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.009228  1.009953 -0.453027 -2.535060
1 -1.080668  0.254548  0.558722  0.001834
2  1.396196 -1.793701  0.486802  0.082754
3 -0.057690 -0.002659 -1.196066 -1.063272
4  1.249679  1.302277  1.860593  0.422878

 4. SLICE DATAFRAME 
Cột so1:
 0     0.009228
1    -1.080668
2     1.396196
3    -0.057690
4     1.249679
5    -0.071639
6     0.338300
7    -0.785188
8    -0.126015
9     0.535498
10   -0.500170
11   -0.137112
12    1.335443
13    1.102694
14   -0.057544
15   -1.269532
16   -0.046083
17    0.665463
18    0.281323
19   -0.131508
Name: so1, dtype: float64
Chọn nhiều dòng :
         so1       so2       so3     

In [9]:
import tensorflow as tf
import numpy as np

print("===== TENSORFLOW BASIC =====")

#  BIỂU DIỄN TENSOR (RANK)
print("\n RANK ")

# Scalar (Rank 0)
r0 = tf.constant(4)
print("Scalar:", r0)

# Vector (Rank 1)
r1 = tf.constant([2.0, 3.0, 4.0])
print("Vector:", r1)

# Matrix (Rank 2)
r2 = tf.constant([[1, 2],
                  [3, 4],
                  [5, 6]])
print("Matrix:\n", r2)

# Tensor 3D (Rank 3)
r3 = tf.constant(np.arange(30).reshape(3, 2, 5))
print("Tensor 3D shape:", r3.shape)


#  THUỘC TÍNH
print("\n===== ATTRIBUTES =====")
print("Shape:", r2.shape)
print("Dtype:", r2.dtype)


#  HÀM TẠO TENSOR
print("\n===== CREATE TENSOR =====")

print("Zeros:\n", tf.zeros([2,3]))
print("Ones:\n", tf.ones([2,3]))
print("Fill:\n", tf.fill([2,2], 7))

print("Linspace:\n", tf.linspace(5.0, 20.0, 5))
print("Range:\n", tf.range(0, 10, 2))


#  RANDOM TENSOR
print("\n===== RANDOM =====")

print("Normal:\n", tf.random.normal([2,3]))
print("Truncated Normal:\n", tf.random.truncated_normal([3,2,2]))
print("Uniform:\n", tf.random.uniform([2,3]))

#  PHÉP TOÁN
print("\n===== OPERATIONS =====")

a = tf.constant([1.0, 4.0])
b = tf.constant([2.0, 3.0])

print("Add:", tf.add(a,b))
print("Subtract:", tf.subtract(a,b))
print("Multiply:", tf.multiply(a,b))
print("Divide:", tf.divide(a,b))

#  HÀM TOÁN HỌC

print("\n===== MATH =====")

x = tf.constant([-4.0, 9.0])

print("Abs:", tf.abs(x))
print("Sqrt:", tf.sqrt(tf.abs(x)))
print("Round:", tf.round(tf.constant([1.2, 2.7])))
print("Ceil:", tf.math.ceil(tf.constant([1.2, 2.7])))
print("Floor:", tf.math.floor(tf.constant([1.2, 2.7])))

#  MA TRẬN

print("\n===== MATRIX =====")

A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[7,8]])

print("Matmul:\n", tf.matmul(A,B))
print("Transpose:\n", tf.transpose(A))
print("Eye:\n", tf.eye(3))
print("Diag:\n", tf.linalg.diag([1,2,3]))


#  VARIABLE

print("\n===== VARIABLE =====")

v = tf.Variable(10)
print("Initial:", v)

v.assign(20)
print("Assign:", v)

v.assign_add(5)
print("Add:", v)

v.assign_sub(3)
print("Sub:", v)

# 6. GRAPH
print("\n===== GRAPH =====")

@tf.function
def compute(a, b):
    return a + b * b

print("Graph result:", compute(3, 5))


print("\n===== HOÀN THÀNH TENSORFLOW =====")

===== TENSORFLOW BASIC =====

 RANK 
Scalar: tf.Tensor(4, shape=(), dtype=int32)
Vector: tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Tensor 3D shape: (3, 2, 5)

===== ATTRIBUTES =====
Shape: (3, 2)
Dtype: <dtype: 'int32'>

===== CREATE TENSOR =====
Zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Fill:
 tf.Tensor(
[[7 7]
 [7 7]], shape=(2, 2), dtype=int32)
Linspace:
 tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
Range:
 tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)

===== RANDOM =====
Normal:
 tf.Tensor(
[[ 1.3270326  -1.0456382   1.327811  ]
 [-0.06500991  1.9629768  -0.21780752]], shape=(2, 3), dtype=float32)
Truncated Normal:
 tf.Tensor(
[[[-0.03537946  0.47489548]
  [ 0.14990932  0.78268975]]

 [[ 1.9770745  -1.6326402 ]
  [-0.9756246  -1.3091097 ]]

 [[-0.7800838  -1.3124955 ]
  [-0.17